<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jscm</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\(</string>
	<key>foldingStopMarker</key>
	<string>\)</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>JavaSc(heme|ript)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tests</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#require</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>_cond-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)\s*(else)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.cond.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.cond.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.cond.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.cond.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>_definition-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(\()\s*(?=\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.variable.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.block.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#_definition-pair</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>_definition-pair</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)([^\s\[\](){}|;#"',`]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.definition-pair.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.variable.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.definition-pair.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.variable.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>_local-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.local.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.local.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#definition</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>_struct-block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)([^\s\[\](){}|;#"',`]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.struct-block.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.struct.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.struct.scheme.javasc-heme-ript</string>
					<key>end</key>
					<string>\]</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.struct-block.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(#?;).*$\n?</string>
					<key>name</key>
					<string>comment.line.semicolon.scheme.javasc-heme-ript</string>
				</dict>
			</array>
		</dict>
		<key>definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()(define)\s+(\()([^\s\[\](){}|;#"',`]+)((?&gt;\s[^)]*|))(\))\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.function.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.scheme.javasc-heme-ript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.scheme.javasc-heme-ript</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.function.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()(define-macro)\s+(\()([^\s\[\](){}|;#"',`]+)\s([^)]*)(\))\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.macro.scheme.javasc-heme-ript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.macro.scheme.javasc-heme-ript</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.macro.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.macro.scheme.javasc-heme-ript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\()(delete-macro)\s+([^\s\[\](){}|;#"',`]+)(\))</string>
					<key>name</key>
					<string>meta.definition.macro.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<false/>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()(define-struct)\s+([^\s\[\](){}|;#"',`]+)\s+(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.struct.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.struct.scheme.javasc-heme-ript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>variable.parameter.struct.scheme.javasc-heme-ript</string>
					<key>end</key>
					<string>\)\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.struct.scheme.javasc-heme-ript</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()(define-datatype)\s+([^\s\[\](){}|;#"',`]+)\s+</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.datatype.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.datatype.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.datatype.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#_struct-block</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()(define|set!)\s([^\s\[\](){}|;#"',`]+)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.variable.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.variable.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.variable.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()(define-macro)\s([^\s\[\](){}|;#"',`]+)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.macro.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.variable.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.macro.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^|(?&lt;=\s))(-?(0|[1-9]\d*)(\.\d+|/[1-9]\d*)?)\b</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;!\\)"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.scheme.javasc-heme-ript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.boolean.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^|(?&lt;=[\s\[\](){}|;#"',`]))(true|false|\#t(rue)?|\#f(alse)?)($|(?=[\s\[\](){}|;#"',`]))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()(lambda)\s+(\()([^\[\](){}|;#"',`]*)(\))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.lambda.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.lambda.scheme.javasc-heme-ript</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.lambda.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()(lambda)\s+([^\s\[\](){}|;#"',`]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.lambda.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.lambda.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.definition.lambda.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()(begin|begin0|if|when|unless)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()(local)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#_local-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()(letrec|let*|let|do)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#_definition-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()(recur|let)\s+([^\s\[\](){}|;#"',`]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.scheme.javasc-heme-ript</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.loop.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#_definition-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()(cond)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.control.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#_cond-block</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(')(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.quoting.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.quoting.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.quoting.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>entity.quoted.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(`)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.quoting.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.quoting.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.quoting.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>name</key>
					<string>entity.quoted.quasi.scheme.javasc-heme-ript</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quasi-quoted</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(^|(?&lt;=[\s\[\](){}|;#"',`]))(void|empty)($|(?=[\s\[\](){}|;#"',`]))</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.functions.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\()(andmap|ormap|apply|compose|build-list|filter|map|foldl1?|foldr1?|for-each|procedure?)\s</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.call.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?&lt;=\()([^\s\[\](){}|;#"',`]+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\[)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.quoting.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>('|`)[^\s\[\](){}|;#"',`]+</string>
					<key>name</key>
					<string>entity.quoted.scheme.javasc-heme-ript</string>
				</dict>
			</array>
		</dict>
		<key>quasi-quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(,@?)(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.quoting.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>entity.expression.scheme.javasc-heme-ript</string>
					<key>end</key>
					<string>(\))\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.quoting.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.expression.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(,@?)([^\s\[\](){}|;#"',`]+)</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\()\s*</string>
					<key>end</key>
					<string>\s*(\))\s*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quasi-quoted</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\[)</string>
					<key>end</key>
					<string>(\])\s*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quasi-quoted</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>quoted</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*(\()</string>
					<key>end</key>
					<string>(\))\s*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\s*(\[)</string>
					<key>end</key>
					<string>(\])\s*</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quoted</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>require</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()(require)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.require.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tests</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()(check-expect)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.open.scheme.javasc-heme-ript</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.check-expect.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>control.operator.bracket.close.scheme.javasc-heme-ript</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#expression</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.scheme.javasc-heme-ript</string>
	<key>uuid</key>
	<string>b9471bee-7dcb-4cfb-86f9-9cc89c0d6a67</string>
</dict>
</plist>
